name: Metrics
on:
  schedule: [{ cron: "0 0 * * 0" }]
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # Authentification
          token: ${{ secrets.METRICS_TOKEN }}

          # Configuration générale
          user: rpokman
          template: classic
          base: header, languages
          config_timezone: Europe/Paris
          config_output: svg
