name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rpokman
          template: classic
          base: "languages"
          config_timezone: Europe/Paris
          config_display: large
          config_output: svg
          plugin_languages: yes
          plugin_languages_ignored: ""
          plugin_languages_sections: most-used
          plugin_languages_limit: 10
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
Forcer l’activation du workflow
