name: Metrics
on:
  schedule: [{ cron: "0 8 * * *" }]
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/metrics.yml

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugin_traffic: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_ignored: >-
            html, css
